services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tbessenreither\FeatureFlagService\Client\FeatureFlagClientInterface:
        alias: Tbessenreither\FeatureFlagService\Client\FeatureFlagClient

    Tbessenreither\FeatureFlagService\Client\FeatureFlagClient:
        arguments:
            $apiUrl: '%feature_flag_service.api_url%'
            $apiKey: '%feature_flag_service.api_key%'
            $timeout: '%feature_flag_service.timeout%'
            $cacheEnabled: '%feature_flag_service.cache_enabled%'
            $cacheTtl: '%feature_flag_service.cache_ttl%'
